name: Ejecutar Pruebas Automatizadas

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    # 2. Configurar Python
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Instalar Firefox de forma limpia (Evita problemas de Snap)
    - name: Configurar Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: 'latest'

    # 4. Instalar las librerías necesarias
    - name: Instalar dependencias de Python
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests

    # 5. Ejecutar tus pruebas aportando el token secreto
   
    
    - name: Ejecutar Prueba 14 (Agregar al carrito)
      env:
        MANTIS_TOKEN: ${{ secrets.MANTIS_TOKEN }}
      run: python prueba14.py
    
    - name: Ejecutar Prueba 15 (Realizar compra)
      env:
        MANTIS_TOKEN: ${{ secrets.MANTIS_TOKEN }}
      run: python prueba15.py

    - name: Ejecutar Prueba 16 (Validar compra)
      env: 
        MANTIS_TOKEN: ${{ secrets.MANTIS_TOKEN }}
      run: python prueba16.py

    - name: Ejecutar Prueba 17 (Validar compra)
      env:
        MANTIS_TOKEN: ${{ secrets.MANTIS_TOKEN }}
      run: python prueba17.py
    
    - name: Ejecutar Prueba 18 (Validar compra)
      env:
        MANTIS_TOKEN: ${{ secrets.MANTIS_TOKEN }}
      run: python prueba18.py

